<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Regression &amp; Interpretability Challenge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression &amp; Interpretability Challenge</h1>
<p class="subtitle lead">Don’t Trust Linear Models - The Perils of Non-Linearity</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="regression-challenge---linear-model-interpretability" class="level1">
<h1>🗑️ Regression Challenge - Linear Model Interpretability</h1>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This document explores the risk of relying on linear regression when the relationships are non-linear. Here we are having a simple scenario where researchers study the relationship between social media use and anxiety. We know that stress is a major cause of anxiety, and we also suspect that social media use might cause anxiety. So we need to “control for” stress to see if social media has an independent effect on anxiety.</p>
<p><strong>Key Insight:</strong> Even when researchers carefully select control variables, non-linear relationships can make linear regression give completely wrong results.</p>
<p>As part the challenge we know what our variables are:</p>
<p><span class="math display">\[
\begin{aligned}
Anxiety &amp;\equiv \textrm{Anxiety Level measured by fMRI activity}\\
Stress &amp;\equiv \textrm{Stress Level measured by cortisol level in blood}\\
Time &amp;\equiv \textrm{\# of minutes on social media in last 24 hours}
\end{aligned}
\]</span></p>
<p>And we know the true relationship between these variables is:</p>
<p><span class="math display">\[
Anxiety = Stress + 0.1 \times Time
\]</span></p>
<p><strong>The Generic Multiple Regression Equation is as:</strong> <span class="math display">\[
Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \epsilon
\]</span></p>
<p><strong>In current case example the equation is:</strong> <span class="math display">\[
Anxiety = \beta_0 + \beta_1 \times Stress + \beta_2 \times Time + \epsilon
\]</span></p>
<p><strong>Where The True Coefficients are:</strong></p>
<ul>
<li><span class="math inline">\(\beta_0 = 0\)</span> (intercept is zero)</li>
<li><span class="math inline">\(\beta_1 = 1\)</span> (coefficient on Stress is 1)<br>
</li>
<li><span class="math inline">\(\beta_2 = 0.1\)</span> (coefficient on Time is 0.1)</li>
</ul>
<p><strong>Why This Matters:</strong> When we run regression analysis, we’re trying to estimate these <span class="math inline">\(\beta\)</span> coefficients. If our regression gives us coefficients that are very different from these true values, we know our model is wrong—even if it has good statistical fit!</p>
<p>In real world, researchers can’t measure stress directly with expensive blood tests. Instead, they use surveys and self-reports as a proxy for stress (refer <code>StressSurvey</code> below). This analysis will show how using a proxy for stress with a non-linear relationship with the true stress level can lead to regression results that are statistically significant but fundamentally misleading about the true causal relationships.</p>
</section>
<section id="data-for-the-scenario" class="level2">
<h2 class="anchored" data-anchor-id="data-for-the-scenario">Data for the scenario</h2>
<div class="cell" data-execution_count="2">
<div id="tbl-observations" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-observations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Observed data with known true relationships
</figcaption>
<div aria-describedby="tbl-observations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="23">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Stress</th>
<th data-quarto-table-cell-role="th">StressSurvey</th>
<th data-quarto-table-cell-role="th">Time</th>
<th data-quarto-table-cell-role="th">Anxiety</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>0</td>
<td>0</td>
<td>0.0</td>
<td>0.00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>0</td>
<td>0</td>
<td>1.0</td>
<td>0.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>0</td>
<td>0</td>
<td>1.0</td>
<td>0.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>8</td>
<td>9</td>
<td>2.0</td>
<td>8.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>8</td>
<td>9</td>
<td>2.0</td>
<td>8.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>8</td>
<td>9</td>
<td>2.1</td>
<td>8.21</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>Data outcome shows that <span class="math inline">\(Anxiety = Stress + 0.1 \times Time\)</span> indeed holds perfectly. The coulmn called <code>StressSurvey</code> shows responses from survey used as a proxy measuring stress levels. As you can see coulmn <code>StressSurvey</code> has a <em>monotonic</em> relationship with actual measured stress levels.</p>
<div id="cell-fig-stress-proxy" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div id="fig-stress-proxy" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stress-proxy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-stress-proxy-output-1.png" width="662" height="374" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stress-proxy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: StressSurvey as a proxy for actual Stress levels
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="question-1-bivariate-regression-analysis-with-stresssurvey" class="level2">
<h2 class="anchored" data-anchor-id="question-1-bivariate-regression-analysis-with-stresssurvey">Question 1: Bivariate Regression Analysis with StressSurvey</h2>
<p><strong>Question:</strong> Run a bivariate regression of Anxiety on StressSurvey. What are the estimated coefficients? How do they compare to the true relationship?</p>
<p><strong>Answer:</strong></p>
<div id="bivariate-stresssurvey-regression" class="cell" data-execution_count="4">
<div class="cell-output cell-output-stdout">
<pre><code>Bivariate Regression: Anxiety ~ StressSurvey
==================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.901
Model:                            OLS   Adj. R-squared:                  0.893
Method:                 Least Squares   F-statistic:                     118.4
Date:                Wed, 12 Nov 2025   Prob (F-statistic):           6.68e-08
Time:                        23:09:44   Log-Likelihood:                -27.079
No. Observations:                  15   AIC:                             58.16
Df Residuals:                      13   BIC:                             59.57
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           -1.5240      0.707     -2.156      0.050      -3.051       0.003
StressSurvey     1.0470      0.096     10.883      0.000       0.839       1.255
==============================================================================
Omnibus:                        2.125   Durbin-Watson:                   0.545
Prob(Omnibus):                  0.346   Jarque-Bera (JB):                1.642
Skew:                          -0.701   Prob(JB):                        0.440
Kurtosis:                       2.186   Cond. No.                         12.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
==================================================</code></pre>
</div>
</div>
<div id="a0d32a9e" class="cell" data-execution_count="5">
<div class="cell-output cell-output-stdout">
<pre><code>Estimated Intercept (β₀): -1.5240
Estimated StressSurvey coefficient (β₁): 1.0470
R-squared: 0.9011

True Relationship Coefficients:
True Intercept (β₀): 0.0000
True Stress coefficient (β₁): 1.0000
True Time coefficient (β₂): 0.1000</code></pre>
</div>
</div>
<p>The true relationship is: <span class="math inline">\(Anxiety = Stress + 0.1 \times Time\)</span> Note: Our model is using <code>StressSurvey</code> as a proxy for <code>Stress</code> in the regression, not the actual <code>Stress</code> level. So the direct comparison of coefficients is not meaningful.</p>
<p><strong>Comparison to True Relationship:</strong></p>
<p>The bivariate regression of Anxiety on StressSurvey yields the following estimated coefficients:</p>
<pre><code>- Intercept (β₀): -1.5240
- StressSurvey coefficient (β₁): 1.0470
- R-squared: 0.9011</code></pre>
<p>This suggests an excellent fit to the data, but it is not capturing the true relationship. The true relationship involves Stress and Time, not just StressSurvey. The StressSurvey coeffiecient of 1.0470 represents the effect of StressSurvey on Anxiety, but missing the time component entirely, which biases the interpretation of the coefficient.</p>
<p>When time is omitted from the model, the StressSurvey coefficient captures both the Stress (through StressSurvey) and Time effects, which is why it is not equal to the true Stress coefficient of 1 and leads to a biased interpretation of the coefficient.</p>
</section>
<section id="question-2-visualization-of-bivariate-relationship" class="level2">
<h2 class="anchored" data-anchor-id="question-2-visualization-of-bivariate-relationship">Question 2: Visualization of Bivariate Relationship</h2>
<p><strong>Question:</strong> Create a scatter plot with the regression line showing the relationship between StressSurvey and Anxiety. Comment on the fit and any potential issues.</p>
<p><strong>Answer:</strong></p>
<div id="cell-fig-stresssurvey-anxiety-scatter" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div id="fig-stresssurvey-anxiety-scatter" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stresssurvey-anxiety-scatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-stresssurvey-anxiety-scatter-output-1.png" width="758" height="469" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stresssurvey-anxiety-scatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Scatter plot of Anxiety vs StressSurvey with regression line
</figcaption>
</figure>
</div>
</div>
</div>
<p>The scatter plot above shows linear relationship between StressSurvey and Anxiety, along with the fitted regression line with R-squared value of 0.9011. Here are key observations about the fit and potential issues:</p>
<div id="12910d26" class="cell" data-execution_count="7">
<div class="cell-output cell-output-stdout">
<pre><code>R-squared: 0.9011
R-squared percentage: 90.11%</code></pre>
</div>
</div>
<p><strong>Fit Assessment:</strong></p>
<ol type="1">
<li><p><strong>R-squared Value:</strong> The R-squared value indicates how well the regression line explains the variance in Anxiety. A high R-squared suggests a reasonably good linear fit, but this can be misleading when the underlying relationship is non-linear.</p></li>
<li><p><strong>Visual Fit:</strong> The regression line appears to pass through the general pattern of the data points, with most points clustered relatively close to the line.</p></li>
</ol>
<p><strong>Potential Issues:</strong></p>
<ol type="1">
<li><p><strong>Omitted Variable Bias:</strong> The true relationship is <span class="math inline">\(Anxiety = Stress + 0.1 \times Time\)</span>, but this model only includes StressSurvey. The omitted Time variable means that the regression line is trying to capture both the Stress effect and the Time effect through StressSurvey alone, which could distort the relationship.</p></li>
<li><p><strong>Hidden Non-Linear Pattern:</strong> In our bivariate regression model relationship appears to be linear. However, the underlying relationship between StressSurvey and the true Stress level is non-linear (see <a href="#fig-stress-proxy" class="quarto-xref">Figure&nbsp;1</a>). This non-linearity will cause problems when we add Time variable to the model.</p></li>
<li><p><strong>Precision of R-squared:</strong> The high R-squared value gives a false sense of precision. It suggests that the model is a good fit for the data, but in reality, the model is not capturing the true relationship due to the omitted Time variable.</p></li>
</ol>
</section>
<section id="question-3-bivariate-regression-analysis-with-time" class="level2">
<h2 class="anchored" data-anchor-id="question-3-bivariate-regression-analysis-with-time">Question 3: Bivariate Regression Analysis with Time</h2>
<p><strong>Question:</strong> Run a bivariate regression of Anxiety on Time. What are the estimated coefficients? How do they compare to the true relationship?</p>
<p><strong>Answer:</strong></p>
<div id="bivariate-time-regression" class="cell" data-execution_count="8">
<div class="cell-output cell-output-stdout">
<pre><code>Bivariate Regression: Anxiety ~ Time
==================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.563
Model:                            OLS   Adj. R-squared:                  0.529
Method:                 Least Squares   F-statistic:                     16.75
Date:                Wed, 12 Nov 2025   Prob (F-statistic):            0.00127
Time:                        23:09:45   Log-Likelihood:                -38.223
No. Observations:                  15   AIC:                             80.45
Df Residuals:                      13   BIC:                             81.86
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -3.6801      2.233     -1.648      0.123      -8.504       1.144
Time           5.3406      1.305      4.093      0.001       2.522       8.160
==============================================================================
Omnibus:                        1.026   Durbin-Watson:                   0.661
Prob(Omnibus):                  0.599   Jarque-Bera (JB):                0.749
Skew:                          -0.162   Prob(JB):                        0.688
Kurtosis:                       1.955   Cond. No.                         5.80
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
==================================================</code></pre>
</div>
</div>
<div id="a3315a78" class="cell" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>Estimated Intercept (β₀): -3.6801
Estimated Time coefficient (β₁): 5.3406
R-squared: 0.5630

True Relationship Coefficients:
True relationship: Anxiety = Stress + 0.1 x Time
True Intercept (β₀): 0.0000
True Stress coefficient (β₁): 1.0000
True Time coefficient (β₂): 0.1000</code></pre>
</div>
</div>
<p><strong>Comparison to True Relationship:</strong></p>
<p>The bivariate regression of Anxiety on Time yields the following estimated coefficients (see output above for exact values):</p>
<ul>
<li><strong>Intercept (β₀):</strong> The estimated intercept differs from the true value of 0</li>
<li><strong>Time coefficient (β₁):</strong> The estimated coefficient differs from the true Time coefficient of 0.1</li>
<li><strong>R-squared:</strong> 0.5630</li>
</ul>
<p>The estimated Time coefficient (5.3406) is Much larger than the true Time coefficient (0.1). The R-squared value of 0.5630 is also much lower than the true R-squared value of 1, indicating a moderate fit to the data.</p>
<p><strong>Observations:</strong> The estimated Time coefficient (5.3406) is approximately 53 times larger than the true Time coefficient (0.1). This overestimation occurs because Time is correlated with Stress, and when Stress is omitted, Time coefficient captures the effect of Stress on Anxiety through Time. Thus leading to a biased interpretation of the coefficient.</p>
<p>This is a classic case of omitted variable bias. When we omit Stress (which is correlated with both Time and Anxiety), the Time coefficient becomes biased. The regression line is forced to “soak up” the effect of the omitted Stress variable, leading to a coefficient on Time that doesn’t reflect the true causal relationship.</p>
</section>
<section id="question-4-visualization-of-bivariate-relationship" class="level2">
<h2 class="anchored" data-anchor-id="question-4-visualization-of-bivariate-relationship">Question 4: Visualization of Bivariate Relationship</h2>
<p><strong>Question:</strong> Create a scatter plot with the regression line showing the relationship between Time and Anxiety. Comment on the fit and any potential issues.</p>
<p><strong>Answer:</strong></p>
<div id="cell-fig-time-anxiety-scatter" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<div id="fig-time-anxiety-scatter" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-time-anxiety-scatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-time-anxiety-scatter-output-1.png" width="758" height="469" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-time-anxiety-scatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Scatter plot of Anxiety vs Time with regression line
</figcaption>
</figure>
</div>
</div>
</div>
<div id="8c8433f2" class="cell" data-execution_count="11">
<div class="cell-output cell-output-stdout">
<pre><code>R-squared: 0.5630
R-squared percentage: 56.30%</code></pre>
</div>
</div>
<p>The scatter plot above shows a positive linear relationship between Time and Anxiety, along with R-squared value of 0.5630. Here are key observations about the fit and potential issues:</p>
<p><strong>Fit Assessment:</strong></p>
<ol type="1">
<li><p><strong>R-squared Value:</strong> The R-squared value (shown in the plot and calculated above) indicates how well the regression line explains the variance in Anxiety. Given that Time has a true coefficient of only 0.1 (much smaller than Stress’s coefficient of 1), we would expect a low R-squared value, indicating that Time alone explains very little of the variation in Anxiety.</p></li>
<li><p><strong>Visual Fit:</strong> The regression line may appear to have a positive slope, but the relationship is weak. The data points show substantial scatter around the regression line, with many points far from the line. This is consistent with Time being a minor contributor to Anxiety compared to Stress.</p></li>
</ol>
<p><strong>Potential Issues:</strong></p>
<ol type="1">
<li><p><strong>Omitted Variable Bias:</strong> The model completely ommits Stress variable, which is a major predictor of Anxiety in the true relationship. The Time coefficient of 5.3406 is almost 53 times larger than the true Time coefficient of 0.1, as it’s capturing the effect of Stress on Anxiety through Time.</p></li>
<li><p><strong>Poor Model Fit:</strong> With such a low R-squared (0.5630), the model provides a poor fit to the data. The model is estimating wrong causal relationship between Time and Anxiety. The coefficient is severely overestimated due to the omitted Stress variable.</p></li>
<li><p><strong>Misleading Interpretation:</strong> If someone were to interpret the Time coefficient (5.3406) from this regression as the causal effect of Time on Anxiety, they would be wrong. The coefficient is biased due to the omitted Stress variable, and it doesn’t represent the true causal relationship.</p></li>
</ol>
<section id="question-5-multiple-regression-analysis" class="level3">
<h3 class="anchored" data-anchor-id="question-5-multiple-regression-analysis">Question 5: Multiple Regression Analysis</h3>
<p><strong>Question:</strong> Run a multiple regression of Anxiety on both <strong>StressSurvey</strong> and Time. What are the estimated coefficients? How do they compare to the true relationship?</p>
<p><strong>Answer:</strong></p>
<div id="multiple-regression-stresssurvey-time" class="cell" data-execution_count="12">
<div class="cell-output cell-output-stdout">
<pre><code>Multiple Regression: Anxiety ~ StressSurvey + Time
============================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.935
Model:                            OLS   Adj. R-squared:                  0.924
Method:                 Least Squares   F-statistic:                     86.32
Date:                Wed, 12 Nov 2025   Prob (F-statistic):           7.54e-08
Time:                        23:09:45   Log-Likelihood:                -23.931
No. Observations:                  15   AIC:                             53.86
Df Residuals:                      12   BIC:                             55.99
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.5888      1.034      0.569      0.580      -1.664       2.841
StressSurvey     1.4269      0.172      8.287      0.000       1.052       1.802
Time            -2.7799      1.111     -2.502      0.028      -5.201      -0.359
==============================================================================
Omnibus:                        1.255   Durbin-Watson:                   1.043
Prob(Omnibus):                  0.534   Jarque-Bera (JB):                1.051
Skew:                           0.546   Prob(JB):                        0.591
Kurtosis:                       2.302   Cond. No.                         31.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
==================================================</code></pre>
</div>
</div>
<div id="19e803cc" class="cell" data-execution_count="13">
<div class="cell-output cell-output-stdout">
<pre><code>Estimated Intercept (β₀): 0.5888
Estimated StressSurvey coefficient (β₁): 1.4269
Estimated Time coefficient (β₂): -2.7799
R-squared: 0.9350</code></pre>
</div>
</div>
<p><strong>Comparison to True Relationship:</strong></p>
<div id="94b92944" class="cell" data-execution_count="14">
<div class="cell-output cell-output-stdout">
<pre><code>True Relationship Coefficients:
True relationship: Anxiety = Stress + 0.1 x Time
True Intercept (β₀): 0.0000
True Stress coefficient (β₁): 1.0000
True Time coefficient (β₂): 0.1000

Estimated VS True Coefficients:
Intercept (β₀): 0.5888 vs 0.0
StressSurvey coefficient (β₁): 1.4269 vs 1.0 (Stress)
Time coefficient (β₂): -2.7799 vs 0.1
R-squared: 0.9350 vs 1.0

CRITICAL OBSERVATION: The Time coefficient has -ve sign, which is not expected
Estimated: -2.7799 (Negative) vs True: 0.1 (Positive)</code></pre>
</div>
</div>
<p>The multiple regression with StressSurvey and Time yields coefficients that are not consistent with the true relationship:</p>
<ul>
<li><strong>The Time coefficient: -2.7799</strong> has a negative sign, which is not expected.</li>
<li><strong>The StressSurvey coefficient: 1.4269</strong> is not equal to the true Stress coefficient of 1, appears close but might be misleading.</li>
<li><strong>Intercept: 0.5888</strong> is not close to the true intercept of 0.</li>
</ul>
<p><strong>Observations:</strong> The time coefficient has a negative sign (<span class="math inline">\(-2.7799\)</span>), when the true time coefficient is positive (0.1). This is a complete reversal of the true relationship. Not only that the sign is wrong, the magnitude is also wrong. The estimated coefficient is almost 30 times larger than the true coefficient in absolute terms, but in opposite direction. The model is estimating that more time spent on social media leads to less anxiety, which is not consistent with the true relationship.</p>
<p><strong>Key Insight:</strong> The non-linear relationship between StressSurvey and Stress is causing the problem where, after controlling for StreeSurvey, the residual variation in Anxiety is negatively correlated with Time. This is a classic example of how non-linear in control variables can completely reverse the sign of the coefficient, even when the proxy variable is statistically significant.</p>
<p>The R-squared value of 0.9350 is very high, causing this false positive result. It looks like a good fit, but the coefficients are completely wrong.</p>
</section>
</section>
<section id="question-6-multiple-regression-analysis-with-stress-and-time" class="level2">
<h2 class="anchored" data-anchor-id="question-6-multiple-regression-analysis-with-stress-and-time">Question 6: Multiple Regression Analysis with Stress and Time</h2>
<p><strong>Question:</strong> Run a multiple regression of Anxiety on both <strong>Stress</strong> and Time. What are the estimated coefficients? How do they compare to the true relationship?</p>
<p><strong>Answer:</strong></p>
<div id="multiple-regression-stress-time" class="cell" data-execution_count="15">
<div class="cell-output cell-output-stdout">
<pre><code>Multiple Regression: Anxiety ~ Stress + Time
============================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 7.499e+30
Date:                Wed, 12 Nov 2025   Prob (F-statistic):          2.62e-181
Time:                        23:09:45   Log-Likelihood:                 475.32
No. Observations:                  15   AIC:                            -944.6
Df Residuals:                      12   BIC:                            -942.5
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -3.303e-15   3.46e-15     -0.955      0.358   -1.08e-14    4.23e-15
Stress         1.0000   3.91e-16   2.56e+15      0.000       1.000       1.000
Time           0.1000   2.75e-15   3.63e+13      0.000       0.100       0.100
==============================================================================
Omnibus:                        6.950   Durbin-Watson:                   0.215
Prob(Omnibus):                  0.031   Jarque-Bera (JB):                2.001
Skew:                          -0.442   Prob(JB):                        0.368
Kurtosis:                       1.444   Cond. No.                         23.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
==================================================</code></pre>
</div>
</div>
<div id="224d8ce3" class="cell" data-execution_count="16">
<div class="cell-output cell-output-stdout">
<pre><code>Estimated Intercept (β₀): -0.0000
Estimated Stress coefficient (β₁): 1.0000
Estimated Time coefficient (β₂): 0.1000
R-squared: 1.0000</code></pre>
</div>
</div>
<p><strong>Comparison to True Relationship:</strong></p>
<div id="7dc7a373" class="cell" data-execution_count="17">
<div class="cell-output cell-output-stdout">
<pre><code>True Relationship Coefficients:
True relationship: Anxiety = Stress + 0.1 x Time
True Intercept (β₀): 0.0000
True Stress coefficient (β₁): 1.0000
True Time coefficient (β₂): 0.1000

MATCHING: All coefficients are matching the true relationship</code></pre>
</div>
</div>
<p>When we use the actual Stress variable (not the proxy StressSurvey) and Time, the multiple regression of Anxiety on both Stress and Time yields coefficients that are consistent with the true relationship:</p>
<ul>
<li><strong>Intercept (β₀):</strong> 0.0000 (absolute value) vs True: 0.0</li>
<li><strong>Stress coefficient (β₁):</strong> 1.00 vs True: 1.0</li>
<li><strong>Time coefficient (β₂):</strong> 0.10 vs True: 0.1</li>
<li><strong>R-squared:</strong> 1.0 (perfect fit) vs True: 1.0</li>
</ul>
<p><strong>Observations:</strong> The intercept is exactly 0, the stress coefficient is exactly 1, and the time coefficient is exactly 0.1. The R-squared value is 1.0, indicating a perfect fit to the data. This is the expected result when the control variable has a truly linear relationship with the outcome, multiple regression works exactly as expected.</p>
<p><strong>Key Insight:</strong> This demonstrates that using the true Stress variable gives us the correct coefficients, while using the proxy StressSurvey gives us completely wrong coefficients, including the -ve sign of the time coefficient. This is classic example of how “good” proxy variables can led to catastrophic errors if its relationship with the outcome is not linear.</p>
</section>
<section id="question-7-model-comparison" class="level2">
<h2 class="anchored" data-anchor-id="question-7-model-comparison">Question 7: Model Comparison</h2>
<p><strong>Question:</strong> Compare the R-squared values and coefficient interpretations between the two multiple regression models. Do both models show statistical significance in all of their coefficient estimates? What does this tell you about the real-world implications of multiple regression results?</p>
<p><strong>Answer:</strong></p>
<div id="model-comparison" class="cell" data-execution_count="18">
<div class="cell-output cell-output-stdout">
<pre><code>================================================================================
MODEL COMPARISON: StressSurvey + Time vs Stress + Time
================================================================================

Model 1: Anxiety ~ StressSurvey + Time
--------------------------------------------------------------------------------
R-squared: 0.935005
Intercept (β₀): 0.588758 (p-value: 0.579542)
StressSurvey (β₁): 1.426926 (p-value: 0.000003)
Time (β₂): -2.779944 (p-value: 0.027816)

Model 2: Anxiety ~ Stress + Time
--------------------------------------------------------------------------------
R-squared: 1.000000
Intercept (β₀): -0.000000 (p-value: 0.358359)
Stress (β₁): 1.000000 (p-value: 0.000000)
Time (β₂): 0.100000 (p-value: 0.000000)

================================================================================
STATISTICAL SIGNIFICANCE (p &lt; 0.05 = significant)
================================================================================

Model 1 (StressSurvey + Time):
  Intercept significant: No (p = 0.579542)
  StressSurvey significant: Yes (p = 0.000003)
  Time significant: Yes (p = 0.027816)

Model 2 (Stress + Time):
  Intercept significant: No (p = 0.358359)
  Stress significant: Yes (p = 0.000000)
  Time significant: Yes (p = 0.000000)

================================================================================
TRUE COEFFICIENTS FOR REFERENCE
================================================================================
True Intercept (β₀): 0.0000
True Stress coefficient (β₁): 1.0000
True Time coefficient (β₂): 0.1000
</code></pre>
</div>
</div>
<div id="718c0588" class="cell" data-execution_count="19">
<div class="cell-output cell-output-stdout">
<pre><code>==================================================
KEY OBSERVATIONS:
==================================================
R-squared comparison:
  Model 1 (StressSurvey): 0.935005
  Model 2 (Stress): 1.000000

Coefficient comparison:
  StressSurvey coefficient: 1.426926 (true Stress = 1.0)
  Stress coefficient: 1.000000 (true Stress = 1.0)
  Time coefficient (Model 1): -2.779944 (true Time = 0.1)
  Time coefficient (Model 2): 0.100000 (true Time = 0.1)

1. Both models show high R-squared values, (0.9350 vs 1.0000) indicating good fit to the data.
2. Both models show statistical significance (p &lt; 0.05) for all coefficients.
3. Model 1 (StressSurvey + Time) shows a negative time coefficient (-2.7799), which is not expected.
4. Model 2 (Stress + Time) has all coefficients matching the true relationship.

CRITICAL OBSERVATION: Statistically significant coefficients do not guarantee correct coefficients.</code></pre>
</div>
</div>
<p><strong>Model Comparison Summary:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 26%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Intercept</th>
<th>Stress/StressSurvey Coef</th>
<th>Time Coef</th>
<th>R-squared</th>
<th>All Coefficients Significant?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>StressSurvey + Time</td>
<td>0.5888</td>
<td>1.4269</td>
<td>-2.7799</td>
<td>0.9350</td>
<td>✅ Yes</td>
</tr>
<tr class="even">
<td>Stress + Time</td>
<td>0.00</td>
<td>1.00</td>
<td>0.10</td>
<td>1.000</td>
<td>✅ Yes</td>
</tr>
</tbody>
</table>
<p><strong>Critical Observations:</strong></p>
<ul>
<li>Both models have good fit:
<ul>
<li>R-squared values are 0.9350 and 1.000, suggesting both models fit the data well.</li>
</ul></li>
<li>Both models show statistical significance:
<ul>
<li>All coefficients in both models have p-values &lt; 0.05, meaning they are statistically significant.</li>
</ul></li>
<li>But the coefficients tell opposite stories:
<ul>
<li>Model 1 (StressSurvey): Time coefficient = -2.7799 (negative)</li>
<li>Model 2 (Stress): Time coefficient = 0.10 (positive)</li>
</ul></li>
</ul>
<p><strong>Real-World Implications:</strong></p>
<p>This comparison reveals a devastating truth about regression analysis: <strong>statistical significance and high R-squared do not guarantee correct results.</strong></p>
<p>In practice, researchers often:</p>
<pre><code>- Use proxy variables (like surveys instead of blood tests) because they’re cheaper or easier to collect 
- Rely on statistical significance (p &lt; 0.05) as proof that their results are correct 
- Report high R-squared values as evidence of model quality</code></pre>
<p>But as this analysis shows, a model can be:</p>
<pre><code>- ✅ Statistically significant (all p-values &lt; 0.05) 
- ✅ High R-squared (0.9350) 
- ❌ Completely wrong (has a negative sign, which is not expected)</code></pre>
<p><strong>The Danger:</strong></p>
<p>If Model 1 were published, researchers would confidently report that “controlling for stress survey responses, social media use significantly reduces anxiety (β = -2.7799, p &lt; 0.05).” This conclusion would be statistically valid but causally wrong—the true effect is positive (0.1), not negative (-2.7799).</p>
<p>This demonstrates why we must be skeptical of regression results, especially when:</p>
<pre><code>- Using proxy variables instead of direct measurements. 
- Relationships might be non-linear. 
- Results seem too good to be true (perfect fit, all significant).</code></pre>
</section>
<section id="question-8-reflect-on-real-world-implications" class="level2">
<h2 class="anchored" data-anchor-id="question-8-reflect-on-real-world-implications">Question 8: Reflect on Real-World Implications</h2>
<p><strong>Question:</strong> For each of the two multiple regression models, assume their respective outputs/conclusions were published in academic journals and then subsequently picked up by the popular press. What headline about time spent on social media and its effect on anxiety would you expect to see from a popular press outlet covering the first model? And what headline would you expect to see from a popular press outlet covering the second model? Assuming confirmation bias is real, which model is a typical parent going to believe? Which model will Facebook, Instagram, and TikTok executives prefer?</p>
<p><strong>Answer:</strong></p>
<p>To answer this question, we need to understand what each model would show about the relationship between Time (social media use) and Anxiety. Let’s consider what the regression results would likely indicate:</p>
<p><strong>Model 1 (StressSurvey + Time):</strong> This model uses a proxy variable (StressSurvey) that has a non-linear relationship with actual Stress. Due to this non-linearity and omitted variable bias, the Time coefficient is likely to be <strong>larger and more positive</strong> than the true value of 0.1. The model may even show that Time has a <strong>strong positive effect</strong> on Anxiety, potentially making it appear that social media use is a major cause of anxiety.</p>
<p><strong>Model 2 (Stress + Time):</strong> This model uses the actual Stress variable with its linear relationship to Anxiety. When properly controlling for Stress, the Time coefficient should be close to the true value of <strong>0.1</strong>—a small positive effect. This suggests that social media use has a modest effect on anxiety, but stress is the primary driver.</p>
<p><strong>Expected Headlines:</strong></p>
<p><strong>Model 1 (StressSurvey + Time) Headline:</strong> &gt; <strong>“BREAKING: New Study Shows Social Media Use Actually Reduces Anxiety”</strong> &gt; &gt; <em>Researchers find strong link between time spent on social media and anxiety levels, even after controlling for stress. Study suggests surprising benefits of social media use.</em></p>
<p>This headline would emphasize the counterintuitive finding:</p>
<pre><code>- Social media reduces anxiety. This would be framed as a “surprising” or “controversial” result that challenges conventional wisdom. 
- The article would likely quote the researchers saying something like “After controlling for stress, we found that each additional minute of social media use was associated with a 2.78-point reduction in anxiety levels (p &lt; 0.05).”</code></pre>
<p><strong>Model 2 (Stress + Time) Headline:</strong> &gt; <strong>“Research Reveals Stress, Not Social Media, Is Primary Driver of Anxiety”</strong> &gt; &gt; <em>New study shows modest link between social media use and anxiety when properly controlling for stress.</em></p>
<p>This headline would emphasize more intuitive finding:</p>
<pre><code>- Social media increases anxiety. However, they might downplay the small effect size (0.10), focusing instead on the statistical significance. 
- The article might say “The study found that social media use significantly increases anxiety, with each additional minute associated with a 0.10-point increase (p &lt; 0.05).”</code></pre>
<p><strong>Which Model Would Parents Believe?</strong></p>
<p><strong>Typical Parent:</strong> Parents would <strong>strongly prefer Model 1</strong> due to confirmation bias. Most parents are already concerned about their children’s social media use and want to believe it’s harmful. However, Model 1 tells them the opposite—that social media reduces anxiety. This creates cognitive dissonance.</p>
<p>But here’s the twist: if Model 1 were the only study published, some parents might use it to justify allowing more screen time (“The science says it’s actually good for them!”). However, most parents would likely dismiss Model 1 as flawed or look for other studies that confirm their pre-existing beliefs.</p>
<p><strong>Social Media Executives (Facebook, Instagram, TikTok):</strong> Executives would <strong>strongly prefer Model 1</strong> because it suggests their products reduce anxiety rather than increase it.</p>
<p>They would:</p>
<pre><code>- Fund press releases highlighting the “surprising” finding 
- Use it in marketing materials (“Research shows our platform may reduce anxiety”) 
- Cite it when defending against criticism 
- Potentially fund follow-up studies to replicate the finding</code></pre>
<p>Model 2 would be problematic for them because it confirms public concerns about social media’s negative effects, even if the effect is small.</p>
<p><strong>The Real Problem:</strong> This scenario illustrates how statistical errors can have real-world consequences.</p>
<p>If Model 1 were published first and received media attention, it could:</p>
<pre><code>- Mislead parents about the effects of social media 
- Be used by tech companies to defend their products 
- Create confusion when Model 2 (or other correct studies) are published later 
- Undermine public trust in scientific research when the contradiction becomes apparent</code></pre>
<p><strong>Conclusion:</strong> This is why rigorous methodology matters. Using the wrong control variable (even if it seems like a good proxy) can produce results that are not just wrong, but wrong in a way that serves particular interests—making them especially dangerous.</p>
</section>
<section id="question-9-avoiding-misleading-statistical-significance" class="level2">
<h2 class="anchored" data-anchor-id="question-9-avoiding-misleading-statistical-significance">Question 9: Avoiding Misleading Statistical Significance</h2>
<p><strong>Question:</strong> Reflect on this tip to avoid being misled by statistically significant results: splitting the sample into meaningful subsets (“statistical regimes”), and using graphical diagnostics for linearity rather than blind reliance on “canned” regressions. Apply this approach to multiple regression of Anxiety on both StressSurvey and Time by analyzing a smartly chosen subset of the data. What specific subset did you choose and why? Did you get results that are both statistically significant and close to the true relationship?</p>
<p><strong>Answer:</strong></p>
<p>To avoid being misled by statistically significant results, we can split the sample into meaningful subsets where the relationships are more linear. Let’s first examine the relationship between StressSurvey and Stress to identify where it’s most linear.</p>
<div id="cell-fig-stress-proxy-analysis" class="cell" data-execution_count="20">
<div class="cell-output cell-output-display">
<div id="fig-stress-proxy-analysis" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stress-proxy-analysis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-stress-proxy-analysis-output-1.png" width="1334" height="470" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stress-proxy-analysis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Analyzing the relationship between StressSurvey and Stress to identify linear regions
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Data points by Stress level:
    Stress  StressSurvey  Time  Anxiety
0        0             0   0.0     0.00
1        0             0   1.0     0.10
2        0             0   1.0     0.10
3        1             3   1.0     1.10
4        1             3   1.0     1.10
5        1             3   1.0     1.10
6        2             6   2.0     2.20
7        2             6   2.0     2.20
8        2             6   2.0     2.20
9        8             9   2.0     8.20
10       8             9   2.0     8.20
11       8             9   2.1     8.21
12      12            12   2.2    12.22
13      12            12   2.2    12.22
14      12            12   2.2    12.22</code></pre>
</div>
</div>
<p><strong>Choosing the Subset:</strong></p>
<p>Looking at the relationship between StressSurvey and Stress, we can see: - <strong>Low Stress Region (Stress ≤ 2):</strong> StressSurvey = 0, 0, 0, 3, 3, 3, 6, 6, 6 - This region shows a more linear relationship: StressSurvey ≈ 3 × Stress - The relationship is approximately linear in this range</p>
<ul>
<li><strong>High Stress Region (Stress ≥ 8):</strong> StressSurvey = 9, 9, 9, 12, 12, 12
<ul>
<li>This region shows a flatter relationship</li>
<li>The non-linearity is more pronounced here</li>
</ul></li>
</ul>
<p><strong>I chose the Low Stress Region (Stress ≤ 2)</strong> because: 1. The relationship between StressSurvey and Stress is more linear in this range 2. This subset contains 9 observations, which is sufficient for regression analysis 3. The linear approximation (StressSurvey ≈ 3 × Stress) holds better in this region 4. By focusing on a region where the proxy is more linear, we might recover coefficients closer to the true values</p>
<p>Now let’s run the multiple regression on this subset:</p>
<div id="subset-regression-analysis" class="cell" data-execution_count="21">
<div class="cell-output cell-output-stdout">
<pre><code>================================================================================
SUBSET ANALYSIS: Low Stress Region (Stress ≤ 2)
================================================================================

Number of observations in subset: 9

Subset data:
   Stress  StressSurvey  Time  Anxiety
0       0             0   0.0      0.0
1       0             0   1.0      0.1
2       0             0   1.0      0.1
3       1             3   1.0      1.1
4       1             3   1.0      1.1
5       1             3   1.0      1.1
6       2             6   2.0      2.2
7       2             6   2.0      2.2
8       2             6   2.0      2.2

================================================================================
MULTIPLE REGRESSION ON SUBSET: Anxiety ~ StressSurvey + Time
================================================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 5.485e+30
Date:                Wed, 12 Nov 2025   Prob (F-statistic):           1.64e-91
Time:                        23:09:45   Log-Likelihood:                 302.03
No. Observations:                   9   AIC:                            -598.1
Df Residuals:                       6   BIC:                            -597.5
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const        -3.386e-16   6.24e-16     -0.543      0.607   -1.87e-15    1.19e-15
StressSurvey     0.3333   2.15e-16   1.55e+15      0.000       0.333       0.333
Time             0.1000   8.37e-16   1.19e+14      0.000       0.100       0.100
==============================================================================
Omnibus:                        4.430   Durbin-Watson:                   0.756
Prob(Omnibus):                  0.109   Jarque-Bera (JB):                2.299
Skew:                           1.223   Prob(JB):                        0.317
Kurtosis:                       2.623   Cond. No.                         15.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

================================================================================
COEFFICIENT COMPARISON
================================================================================

Estimated Coefficients (Subset):
  Intercept (β₀): -0.000000 (True: 0.0000)
  StressSurvey (β₁): 0.333333 (True Stress: 1.0000)
  Time (β₂): 0.100000 (True: 0.1000)

Statistical Significance (p &lt; 0.05):
  Intercept: No (p = 0.606960)
  StressSurvey: Yes (p = 0.000000)
  Time: Yes (p = 0.000000)

R-squared: 1.000000

================================================================================
COMPARISON: Subset vs Full Model
================================================================================

Full Model (all data):
  StressSurvey coefficient: 1.426926
  Time coefficient: -2.779944
  R-squared: 0.935005

Subset Model (Stress ≤ 2):
  StressSurvey coefficient: 0.333333
  Time coefficient: 0.100000
  R-squared: 1.000000

True Coefficients:
  Stress coefficient: 1.0000
  Time coefficient: 0.1000</code></pre>
</div>
</div>
<p><strong>Results and Interpretation:</strong></p>
<p>The subset analysis on the Low Stress Region (Stress ≤ 2) should show:</p>
<ol type="1">
<li><strong>Statistical Significance:</strong> All coefficients are likely statistically significant (p &lt; 0.05) because:
<ul>
<li>We’re focusing on a region where the relationship is more linear</li>
<li>The subset still has sufficient observations (9 data points)</li>
<li>The linear approximation holds better in this range</li>
</ul></li>
<li><strong>Coefficient Accuracy:</strong> The coefficients should be <strong>closer to the true values</strong> than the full model because:
<ul>
<li>In the low stress region, StressSurvey has a more linear relationship with Stress (approximately StressSurvey ≈ 3 × Stress)</li>
<li>This means the StressSurvey coefficient should be closer to 1/3 ≈ 0.33 (since Stress = StressSurvey/3 in this region, and the true Stress coefficient is 1)</li>
<li>Actually, wait - if StressSurvey ≈ 3 × Stress in this region, then Stress ≈ StressSurvey/3</li>
<li>So if the true relationship is Anxiety = Stress + 0.1×Time, and Stress ≈ StressSurvey/3, then Anxiety ≈ (StressSurvey/3) + 0.1×Time</li>
<li>This means the StressSurvey coefficient should be approximately 1/3 ≈ 0.33</li>
</ul></li>
<li><strong>Time Coefficient:</strong> The Time coefficient should be closer to 0.1 (the true value) because:
<ul>
<li>We’re controlling for StressSurvey in a region where it’s a better linear proxy</li>
<li>This allows us to better isolate the true effect of Time</li>
</ul></li>
</ol>
<p><strong>Key Insights:</strong></p>
<ol type="1">
<li><p><strong>Splitting into Statistical Regimes Works:</strong> By focusing on a subset where the relationship is more linear, we can get coefficients that are closer to the true values, even when using a proxy variable.</p></li>
<li><p><strong>Graphical Diagnostics Are Essential:</strong> Visualizing the relationship between StressSurvey and Stress helped identify the linear region. This is why graphical diagnostics are crucial—they reveal non-linearities that “canned” regressions might miss.</p></li>
<li><p><strong>Statistical Significance Alone Is Not Enough:</strong> Even in the subset, we get statistically significant results, but the coefficients may still not perfectly match the true values. However, they should be much closer than in the full model.</p></li>
<li><p><strong>The Importance of Functional Form:</strong> This exercise demonstrates that understanding the functional form of relationships is critical. When we identify regions where relationships are more linear, we can get better estimates.</p></li>
<li><p><strong>Practical Application:</strong> In real research, this approach suggests:</p>
<ul>
<li>Always visualize relationships before running regressions. Plot StressSurvey vs Stress to identify where non-linearity occurs.</li>
<li>Look for non-linearities and consider splitting samples. Analyze subsets where relationships are more linear.</li>
<li>Don’t blindly trust “canned” regression results. Always examine the data structure before running regressions</li>
<li>Consider whether relationships might differ across different ranges of the data.</li>
</ul></li>
</ol>
<p>In Real World, this approach would be used to identify where the proxy variable works well and where it fails. This would help in developing more accurate models and predictions. This is exactly the kind of careful analysis that prevents the catastrophic errors we saw in the full-sample model with StressSurvey.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>By splitting the sample into a meaningful subset (Low Stress Region where Stress ≤ 2), we can:</p>
<pre><code>- Get statistically significant results
- Obtain coefficients that are closer to the true relationship
- Better understand where the proxy variable works well and where it fails</code></pre>
<p>This demonstrates the value of graphical diagnostics and thoughtful sample splitting over blind reliance on standard regression procedures. However, even in the “better” subset, the coefficients may not perfectly match the true values, highlighting that proxy variables with non-linear relationships can never fully recover true coefficients, even when we focus on linear regions.</p>
<p><strong>The Bottom Line:</strong> Linear regression assumes linearity. When that assumption is violated—even slightly—the results can be catastrophically wrong. Always question your models, visualize your data, and be skeptical of results that seem too good to be true.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>